/*Malika Sharma 
 *Making Purchases Program 
 *17/09/2019
 *author @masha2470
 */

/**
 *
 *
 */
public class MakingPurchasesFrame extends javax.swing.JFrame {

    /**
     * Creates new form MakingPurchasesFrame
     */
    public MakingPurchasesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        Tittle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pizza1 = new javax.swing.JLabel();
        pizza2 = new javax.swing.JLabel();
        pizza3 = new javax.swing.JLabel();
        pizza4 = new javax.swing.JLabel();
        textPizza1 = new javax.swing.JTextField();
        textPizza2 = new javax.swing.JTextField();
        textPizza3 = new javax.swing.JTextField();
        textPizza4 = new javax.swing.JTextField();
        taxes1 = new javax.swing.JLabel();
        labelDisplay1 = new javax.swing.JLabel();
        subtotal = new javax.swing.JLabel();
        labelDisplay2 = new javax.swing.JLabel();
        grandtotal = new javax.swing.JLabel();
        labelDisplay3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        img = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setFont(new java.awt.Font("Goudy Stout", 0, 11)); // NOI18N

        Tittle.setFont(new java.awt.Font("Lapidary333 Blk BT", 0, 24)); // NOI18N
        Tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tittle.setText("Malika's Pizzeria");
        Tittle.setMaximumSize(new java.awt.Dimension(100, 200));

        jLabel2.setText("Enter in the amount of each type of pizza you would like to purchase and hit calculate! ");

        pizza1.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        pizza1.setText("Cheese Pizza ($1.50)");

        pizza2.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        pizza2.setText("Pepperoni Pizza ($1.50) ");

        pizza3.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        pizza3.setText("Hawaiin Pizza ($2.00) ");

        pizza4.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        pizza4.setText("Chicken Alfredo Pizza ($2.50)");

        textPizza1.setText("0");

        textPizza2.setText("0");
        textPizza2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPizza2ActionPerformed(evt);
            }
        });

        textPizza3.setText("0");
        textPizza3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPizza3ActionPerformed(evt);
            }
        });

        textPizza4.setText("0");
        textPizza4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPizza4ActionPerformed(evt);
            }
        });

        taxes1.setFont(new java.awt.Font("Zolano Sans BTN", 1, 13)); // NOI18N
        taxes1.setText("Taxes (13%)");

        labelDisplay1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelDisplay1.setText("$0.00");

        subtotal.setFont(new java.awt.Font("Zolano Sans BTN", 1, 13)); // NOI18N
        subtotal.setText("Subtotal ");

        labelDisplay2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelDisplay2.setText("$0.00");

        grandtotal.setFont(new java.awt.Font("Zolano Sans BTN", 1, 13)); // NOI18N
        grandtotal.setText("Grand Total");

        labelDisplay3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelDisplay3.setText("$0.00");

        jButton1.setText("Calculate ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza (1).png"))); // NOI18N
        img.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pizza4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPizza4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(pizza1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textPizza1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textPizza3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(pizza2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textPizza2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(grandtotal)
                                    .addComponent(subtotal, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(taxes1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(pizza3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDisplay2)
                            .addComponent(labelDisplay1)
                            .addComponent(labelDisplay3))))
                .addGap(166, 166, 166))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jButton1)
                        .addGap(53, 53, 53)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pizza1)
                    .addComponent(textPizza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxes1)
                    .addComponent(labelDisplay1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pizza2)
                            .addComponent(textPizza2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtotal)
                            .addComponent(labelDisplay2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pizza3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(grandtotal)
                                .addComponent(labelDisplay3))
                            .addComponent(textPizza3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pizza4))
                    .addComponent(textPizza4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPizza2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPizza2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPizza2ActionPerformed
    
    private void textPizza3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPizza3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPizza3ActionPerformed

    private void textPizza4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPizza4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPizza4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double pizza1 = Double.parseDouble(textPizza1.getText());
        double pizza2 = Double.parseDouble(textPizza2.getText()); 
        double pizza3 = Double.parseDouble(textPizza3.getText()); 
        double pizza4 = Double.parseDouble(textPizza4.getText());
        double taxes1 = (pizza1 *1.50 + pizza2*1.50 + pizza3*2.00 + pizza4*2.50) * 0.13;
        double subtotal = (pizza1 *1.50 + pizza2*1.50 + pizza3*2.00 + pizza4*2.50);
        double grandtotal = taxes1 + subtotal; 
        taxes1 = taxes1 * 100;
        taxes1 = Math.round(taxes1);
        taxes1 = taxes1 / 100;
        subtotal = subtotal * 100;
        subtotal = Math.round(subtotal);
        subtotal = subtotal / 100;
        grandtotal = grandtotal * 100;
        grandtotal = Math.round(grandtotal);
        grandtotal= grandtotal / 100;
        labelDisplay1.setText("$" + taxes1); 
        labelDisplay2.setText("$" + subtotal); 
        labelDisplay3.setText("$" + grandtotal); 
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
    }//GEN-LAST:event_buttonDisplayActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakingPurchasesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakingPurchasesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakingPurchasesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakingPurchasesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakingPurchasesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tittle;
    private javax.swing.JLabel grandtotal;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JLabel labelDisplay1;
    private javax.swing.JLabel labelDisplay2;
    private javax.swing.JLabel labelDisplay3;
    private javax.swing.JLabel pizza1;
    private javax.swing.JLabel pizza2;
    private javax.swing.JLabel pizza3;
    private javax.swing.JLabel pizza4;
    private javax.swing.JLabel subtotal;
    private javax.swing.JLabel taxes1;
    private javax.swing.JTextField textPizza1;
    private javax.swing.JTextField textPizza2;
    private javax.swing.JTextField textPizza3;
    private javax.swing.JTextField textPizza4;
    // End of variables declaration//GEN-END:variables
}
